replicaCount: 1
term: cs261-s26
image:
  repository: registry.digitalocean.com/cs261-s26/<student-id-here>
  tag: latest
  pullPolicy: Always

service:
  port: 3100
  type: ClusterIP

redis:
  host: <redis-host-name-here>
  port: 6379
  expire_sec: 10

mongo:
  host: <mongo-host-name-here>
  port: 27017
  collection: <collection-name-here>

gameServer:
  port: 4200
