apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  MONGO_HOST: "{{ .Values.mongo.host }}"
  MONGO_PORT: "{{ .Values.mongo.port }}"
  MONGO_DB: "{{ .Release.Namespace }}-db"
  MONGO_COLLECTION: "{{ .Values.mongo.collection }}"
  REDIS_PREFIX: "{{ .Release.Namespace }}"
  REDIS_HOST: "{{ .Values.redis.host }}"
  REDIS_PORT: "{{ .Values.redis.port }}"
  SESSION_EXPIRES_SEC: "{{ .Values.redis.expire_sec }}"
  SERVICE_PORT: "{{ .Values.service.port }}"
  GAME_PORT: "{{ .Values.gameServer.port }}"